/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.DAOAuditoria;
import Modelo.AuditoriaMovimiento;
import Modelo.CRUD_Inventario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author linco
 */
public class ModificarInventario extends javax.swing.JFrame {

    /**
     * Creates new form InventarioInsertar
     */
    AuditoriaMovimiento audi = new AuditoriaMovimiento();
    DAOAuditoria dao = new DAOAuditoria();

    public ModificarInventario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jComboBoxCategorias = new javax.swing.JComboBox<>();
        jMiniLogo = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jLabelStock = new javax.swing.JLabel();
        jLabelPriceUnidad = new javax.swing.JLabel();
        jLabelCategoria = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jTextNombre = new javax.swing.JTextField();
        jTextStock = new javax.swing.JTextField();
        jTextPrecioUnid = new javax.swing.JTextField();
        jTextCategoria = new javax.swing.JTextField();
        jLabelID = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMostrar = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonExportar = new javax.swing.JButton();
        jButtonEliminar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonSalir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButtonAñadir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestor Inventario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFocusCycleRoot(false);
        setMinimumSize(getPreferredSize());
        setPreferredSize(new java.awt.Dimension(910, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(910, 510));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMinimumSize(new java.awt.Dimension(910, 510));
        jPanel1.setPreferredSize(new java.awt.Dimension(910, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto Black", 1, 14)); // NOI18N
        jLabel1.setText("Selecciona una tabla a mostrar");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, 36));

        jComboBoxCategorias.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jComboBoxCategorias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Seleccionar Tabla--", "Ropa", "Alimentos", "Deporte", "Tecnologia", "Limpieza" }));
        jComboBoxCategorias.setToolTipText("Selecciona una categoría para mostrar su tabla");
        jComboBoxCategorias.setBorder(null);
        jComboBoxCategorias.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCategoriasActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBoxCategorias, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 170, -1));

        jMiniLogo.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jMiniLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMiniLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/logistic icon mini.png"))); // NOI18N
        jMiniLogo.setText("Gestor Inventario");
        jPanel1.add(jMiniLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 30));

        jLabelNombre.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelNombre.setText("Nombre");
        jLabelNombre.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, -1, -1));

        jLabelStock.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelStock.setText("Stock");
        jLabelStock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 130, -1, -1));

        jLabelPriceUnidad.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelPriceUnidad.setText("Precio/Unidad");
        jLabelPriceUnidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelPriceUnidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, -1, -1));

        jLabelCategoria.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelCategoria.setText("Categoria");
        jLabelCategoria.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, -1, -1));

        jTextID.setEditable(false);
        jTextID.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextID.setEnabled(false);
        jTextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIDActionPerformed(evt);
            }
        });
        jPanel1.add(jTextID, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 70, 240, -1));

        jTextNombre.setEditable(false);
        jTextNombre.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextNombre.setEnabled(false);
        jTextNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNombreActionPerformed(evt);
            }
        });
        jPanel1.add(jTextNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 100, 240, -1));

        jTextStock.setEditable(false);
        jTextStock.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextStock.setEnabled(false);
        jTextStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextStockActionPerformed(evt);
            }
        });
        jPanel1.add(jTextStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 240, -1));

        jTextPrecioUnid.setEditable(false);
        jTextPrecioUnid.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextPrecioUnid.setEnabled(false);
        jTextPrecioUnid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPrecioUnidActionPerformed(evt);
            }
        });
        jPanel1.add(jTextPrecioUnid, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 240, -1));

        jTextCategoria.setEditable(false);
        jTextCategoria.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jTextCategoria.setEnabled(false);
        jPanel1.add(jTextCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 240, -1));

        jLabelID.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabelID.setText("ID");
        jLabelID.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelID.setFocusCycleRoot(true);
        jLabelID.setFocusable(false);
        jLabelID.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabelID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        TablaMostrar.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        TablaMostrar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        TablaMostrar.setEnabled(false);
        TablaMostrar.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablaMostrarAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        TablaMostrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMostrarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaMostrar);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 694, 250));

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        jButtonExportar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonExportar.setText("Exportar");
        jButtonExportar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonExportar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExportarActionPerformed(evt);
            }
        });

        jButtonEliminar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonEliminar.setText("Eliminar");
        jButtonEliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonEliminar.setEnabled(false);
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });

        jButtonLimpiar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonLimpiar.setText("Limpiar");
        jButtonLimpiar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonLimpiar.setEnabled(false);
        jButtonLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiarActionPerformed(evt);
            }
        });

        jButtonActualizar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });

        jButtonGuardar.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonGuardar.setEnabled(false);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Roboto Medium", 1, 12)); // NOI18N
        jLabel2.setText("Operaciones");

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jLabel3.setText("Salida");

        jButtonSalir.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jButtonAñadir.setFont(new java.awt.Font("Roboto Medium", 0, 12)); // NOI18N
        jButtonAñadir.setText("Añadir");
        jButtonAñadir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAñadir.setEnabled(false);
        jButtonAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAñadirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonActualizar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jButtonGuardar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonLimpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonAñadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jButtonExportar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonAñadir, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExportar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 0, -1, 480));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 540));

        setSize(new java.awt.Dimension(926, 544));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextNombreActionPerformed

    private void jTextStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextStockActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void TablaMostrarAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablaMostrarAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_TablaMostrarAncestorAdded

    private void TablaMostrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMostrarMouseClicked
        CRUD_Inventario tb = new CRUD_Inventario();
        tb.SeleccionarElemento(TablaMostrar, jTextID, jTextNombre, jTextStock, jTextPrecioUnid, jTextCategoria);
    }//GEN-LAST:event_TablaMostrarMouseClicked

    private void jTextPrecioUnidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPrecioUnidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPrecioUnidActionPerformed

    private void jTextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIDActionPerformed

    private void jComboBoxCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCategoriasActionPerformed
        String opcionSeleccionada = jComboBoxCategorias.getSelectedItem().toString();
        CRUD_Inventario tb = new CRUD_Inventario();
        switch (opcionSeleccionada) {
            case "--Seleccionar Tabla--":
                JOptionPane.showMessageDialog(null, "Por favor selecciona una categoría válida");
                break;
            case "Ropa":
                tb.mostrarTablaRopa(TablaMostrar);
                break;
            case "Alimentos":
                tb.mostrarTablaAlimentos(TablaMostrar);
                break;
            case "Deporte":
                tb.mostrarTablaDeporte(TablaMostrar);
                break;
            case "Tecnologia":
                tb.mostrarTablaElectronico(TablaMostrar);
                break;
            case "Limpieza":
                tb.mostrarTablaLimpieza(TablaMostrar);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Categoría no reconocida");
        }
    }//GEN-LAST:event_jComboBoxCategoriasActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        TablaMostrar.setEnabled(true);
        jTextID.setEditable(true);
        jTextID.setEnabled(true);
        jTextNombre.setEditable(true);
        jTextNombre.setEnabled(true);
        jTextStock.setEditable(true);
        jTextStock.setEnabled(true);
        jTextPrecioUnid.setEditable(true);
        jTextPrecioUnid.setEnabled(true);
        jTextCategoria.setEditable(true);
        jTextCategoria.setEnabled(true);
        jButtonLimpiar.setEnabled(true);
        jButtonEliminar.setEnabled(true);
        jButtonGuardar.setEnabled(true);
        jButtonAñadir.setEnabled(true);
        registrarAuditoria("actualizar");


    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed
        CRUD_Inventario tb = new CRUD_Inventario();

        String tablaSeleccionada = jComboBoxCategorias.getSelectedItem().toString();

        if (tablaSeleccionada.equals("--Seleccionar Tabla--")) {
            JOptionPane.showMessageDialog(null, "⚠️ Selecciona una tabla válida primero.");
            return;
        }

        boolean seElimino;
        seElimino = tb.EliminarRegistro(tablaSeleccionada, jTextID);

        if (seElimino) {
            // Refrescar tabla según categoría
            switch (tablaSeleccionada) {
                case "Ropa":
                    tb.mostrarTablaRopa(TablaMostrar);
                    break;
                case "Alimentos":
                    tb.mostrarTablaAlimentos(TablaMostrar);
                    break;
                case "Deporte":
                    tb.mostrarTablaDeporte(TablaMostrar);
                    break;
                case "Tecnologia":
                    tb.mostrarTablaElectronico(TablaMostrar);
                    break;
                case "Limpieza":
                    tb.mostrarTablaLimpieza(TablaMostrar);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Categoría no reconocida");
            }
        }
        // Limpiar celdas al finalizar guardado
        jTextID.setText("");
        jTextNombre.setText("");
        jTextStock.setText("");
        jTextPrecioUnid.setText("");
        jTextCategoria.setText("");

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonExportarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExportarActionPerformed
        javax.swing.table.TableModel modelo = TablaMostrar.getModel();
        VentanaReporte ventana = new VentanaReporte(modelo);
        ventana.setVisible(true);
        registrarAuditoria("exportar");


    }//GEN-LAST:event_jButtonExportarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        CRUD_Inventario tb = new CRUD_Inventario();

        String tablaSeleccionada = jComboBoxCategorias.getSelectedItem().toString();

        if (tablaSeleccionada.equals("--Seleccionar Tabla--")) {
            JOptionPane.showMessageDialog(null, "⚠️ Selecciona una tabla válida primero.");
            return;
        }

        boolean seGuardo;
        seGuardo = tb.actualizarRegistro(tablaSeleccionada, jTextID, jTextNombre, jTextStock, jTextPrecioUnid, jTextCategoria);

        if (seGuardo) {
            // Refrescar tabla según categoría
            switch (tablaSeleccionada) {
                case "Ropa":
                    tb.mostrarTablaRopa(TablaMostrar);
                    break;
                case "Alimentos":
                    tb.mostrarTablaAlimentos(TablaMostrar);
                    break;
                case "Deporte":
                    tb.mostrarTablaDeporte(TablaMostrar);
                    break;
                case "Tecnologia":
                    tb.mostrarTablaElectronico(TablaMostrar);
                    break;
                case "Limpieza":
                    tb.mostrarTablaLimpieza(TablaMostrar);
                    break;
                default:
                    JOptionPane.showMessageDialog(null, "Categoría no reconocida");
            }
        }
        // Limpiar celdas al finalizar guardado
        jTextID.setText("");
        jTextNombre.setText("");
        jTextStock.setText("");
        jTextPrecioUnid.setText("");
        jTextCategoria.setText("");

        // Desactivar campos
        TablaMostrar.setEnabled(false);
        TablaMostrar.clearSelection();
        jTextID.setEditable(false);
        jTextID.setEnabled(false);
        jTextNombre.setEditable(false);
        jTextNombre.setEnabled(false);
        jTextStock.setEditable(false);
        jTextStock.setEnabled(false);
        jTextPrecioUnid.setEditable(false);
        jTextPrecioUnid.setEnabled(false);
        jTextCategoria.setEditable(false);
        jTextCategoria.setEnabled(false);
        jButtonLimpiar.setEnabled(false);
        jButtonEliminar.setEnabled(false);
        jButtonGuardar.setEnabled(false);
        jButtonAñadir.setEnabled(false);

        registrarAuditoria("guardar");
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiarActionPerformed
        jTextID.setText("");
        jTextNombre.setText("");
        jTextStock.setText("");
        jTextPrecioUnid.setText("");
        jTextCategoria.setText("");

        registrarAuditoria("limpiar");

    }//GEN-LAST:event_jButtonLimpiarActionPerformed

    private void jButtonAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAñadirActionPerformed
        CRUD_Inventario tb = new CRUD_Inventario();

        String tablaSeleccionada = jComboBoxCategorias.getSelectedItem().toString();

        if (tablaSeleccionada.equals("--Seleccionar Tabla--")) {
            JOptionPane.showMessageDialog(null, "⚠️ Selecciona una tabla válida primero.");
            return;
        }

        tb.InsertarRegistro(tablaSeleccionada, jTextID, jTextNombre, jTextStock, jTextPrecioUnid, jTextCategoria);
        switch (tablaSeleccionada) {
            case "Ropa":
                tb.mostrarTablaRopa(TablaMostrar);
                break;
            case "Alimentos":
                tb.mostrarTablaAlimentos(TablaMostrar);
                break;
            case "Deporte":
                tb.mostrarTablaDeporte(TablaMostrar);
                break;
            case "Tecnologia":
                tb.mostrarTablaElectronico(TablaMostrar);
                break;
            case "Limpieza":
                tb.mostrarTablaLimpieza(TablaMostrar);
                break;
            default:
                JOptionPane.showMessageDialog(null, "Categoría no reconocida");
                registrarAuditoria("añadir");

        }
    }//GEN-LAST:event_jButtonAñadirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarInventario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ModificarInventario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaMostrar;
    private javax.swing.JButton jButtonActualizar;
    private javax.swing.JButton jButtonAñadir;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JButton jButtonExportar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JComboBox<String> jComboBoxCategorias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCategoria;
    private javax.swing.JLabel jLabelID;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelPriceUnidad;
    private javax.swing.JLabel jLabelStock;
    private javax.swing.JLabel jMiniLogo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextCategoria;
    private javax.swing.JTextField jTextID;
    private javax.swing.JTextField jTextNombre;
    private javax.swing.JTextField jTextPrecioUnid;
    private javax.swing.JTextField jTextStock;
    // End of variables declaration//GEN-END:variables

    private void registrarAuditoria(String accion) {

        audi.setTipo(jComboBoxCategorias.getSelectedItem().toString());
        audi.setMovimiento(accion);
        if (dao.insertar(audi)) {
        }
    }
}
